### ISSUE TITLE
关于url的路径问题

### ISSUE THREAD

**Issue by HeUncle** [fctony/Wechat-Emall#3]
url: 'https://api.it120.cc/' + that.globalData.subDomain + '/user/check-token',
访问不到这个路径

**Comment by zhuangjie666** [comment]
那个路径是外部的API 路径 应该是类似进销存的后台 或者说是商品管理后台， 这个有很多东西没有完善。 商品管理，支付接口 都没有的

**Comment by zhuangjie666** [comment]
> url: 'https://api.it120.cc/' + that.globalData.subDomain + '/user/check-token',
> 访问不到这个路径

那个路径是外部的API 路径 应该是类似进销存的后台 或者说是商品管理后台， 这个有很多东西没有完善。 商品管理，支付接口 都没有的

**Comment by fctony** [comment]
在你的微信开发者工具打开的话，你需要在微信平台后台配置上这个域名https://api.it120.cc，才能在你的项目里访问
